sudo: false

language: php

rvm:
  - 2.2.0

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

branches:
  except:
    - 1.8.9
    - 1.8.8
    - 1.8.7
    - develop

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env:
        - COMPOSER_PROCESS_TIMEOUT=1200
        - TEST_CHECK=true
        - CS_CHECK=true
        - CC_CHECK=false
    - php: 7.0
      env:
        - COMPOSER_PROCESS_TIMEOUT=1200
        - TEST_CHECK=true
        - CS_CHECK=true
        - CC_CHECK=false
    - php: 7.1
      env:
        - COMPOSER_PROCESS_TIMEOUT=1200
        - TEST_CHECK=true
        - CS_CHECK=true
        - CC_CHECK=false
    - php: 7.2
      env:
        - COMPOSER_PROCESS_TIMEOUT=1200
        - TEST_CHECK=true
        - CS_CHECK=true
        - CC_CHECK=false
    - php: 7.3
      env:
        - COMPOSER_PROCESS_TIMEOUT=1200
        - TEST_CHECK=true
        - CS_CHECK=true
        - CC_CHECK=false
    - php: 7.4
      env:
        - COMPOSER_PROCESS_TIMEOUT=1200
        - TEST_CHECK=true
        - CS_CHECK=true
        - CC_CHECK=false
    - php: 8.0
      env:
        - TEST_CHECK=true
        - CS_CHECK=true
        - CC_CHECK=false
  allow_failures:
    - php: 8.0

before_install:
  - travis_retry composer self-update
  - if [[ $TEST_CHECK_54 == 'true' ]]; then rm $TRAVIS_BUILD_DIR/composer.json && mv $TRAVIS_BUILD_DIR/composer.php54.json $TRAVIS_BUILD_DIR/composer.json ; fi
  - if [[ -z "$TEST_CHECK_COVER" ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
    
install:
  - travis_retry composer install --no-interaction

before_script:
  - if [[ $CC_CHECK == 'true' ]]; then $TRAVIS_BUILD_DIR/bin/selenium-setup.sh ; fi
  - if [[ $CC_CHECK == 'true' ]]; then npm install -g se-interpreter ; fi

script:
  - if [[ $CC_CHECK == 'true' ]]; then se-interpreter tests/selenium/se-interpreter_config.json ; fi
  - if [[ $TEST_CHECK == 'true' || $TEST_CHECK_54 == 'true' ]]; then composer test ; fi
  - if [[ $TEST_CHECK_COVER == 'true' ]]; then composer test-cover ; fi
  - if [[ $CS_CHECK == 'true' ]]; then composer cs ; fi
  - if [[ $TEST_CHECK_COVER == 'true' ]]; then if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT ; fi ; fi

#after_script:
  #- if [[ $TEST_CHECK_COVER == 'true' ]]; then mv build/logs/clover.xml clover.xml ; fi
  #- if [[ $TEST_CHECK_COVER == 'true' ]]; then ./cc-test-reporter after-build --coverage-input-type clover --id 12345 --exit-code $TRAVIS_TEST_RESULT ; fi

#after_success:
  #- if [[ $TEST_CHECK_COVER == 'true' ]]; then composer test-report ; fi
